volumes:
  static:
  media:

services:
  backend:
    build: ./kittygram_backend
    ports:
      - "8000:8000"
    env_file: .env.example
    volumes:
      - static:/app/collected_static
      - media:/app/media

  frontend:
    build: ./kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static:/staticfiles
      - media:/media
    depends_on:
      - backend
      - frontend
    user: root