# Generated by Django 5.1.1 on 2026-05-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_favorite_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
